### ISSUE TITLE
Multiple errors when enabling noImplicitAny

### ISSUE THREAD

**Issue by AndersHogqvist** [pixilab/blocks-script#19]
I'm trying to create a feed but can't get it to work. I have used the collection fees example from your wiki as a base but when I compile it I get the following error:
Type 'ListItem' provides no match for the signature 'new (...args: any[]): ListItem'

I've tried to figure out why and noticed that in the tsconfig file included with the example you have noImplicitAny enabled so I tried to enable that on our Blocks server as well. That however produced 62 errors when compiling!

Blocks version: 5.5
Script version: downloaded from GitHub 8/3
TypeScript version: 4.6.2
Node version: 16.4.0

**Comment by AndersHogqvist** [comment]
Ops, my bad

**Comment by TheWizz** [comment]
Out of curiosity, what was your problem caused by? Perhaps there something we can improve to avoid others frmo bumping into similar issues?

**Comment by AndersHogqvist** [comment]
Well, to honest I don't know if the problem with all the errors is solved but I found why my feed code failed. It was really silly, I had 'readonly listType: ListItem' instead of 'readonly listType = ListItem'.

After fixing that I didn't check if I could enable noImplicitAny. Honestly I doubt that it would work now since the errors I got wasn't related to my code, I will check tomorrow. Perhaps you should set it to false in the example code since it's obviously not required. In fact, why not just have the necessary files in the zip and instruct the user to download the rest of the script folder from here if they not already have it? By doing that you wouldn't have to update those zip files everytime you update the rest.

**Comment by TheWizz** [comment]
We always have noImplicitAny set to true. Setting it to false would only be useful if you need to incorporate code that has no type definitions (e.g., plain old JavaScript code where you've just changed .js to .ts). This has no impact on the generated code either way, but only affects the "strictness" of the typescript compiler.

**Comment by AndersHogqvist** [comment]
How come it's set to false in your repository here then?

**Comment by TheWizz** [comment]
It seems a few user-contributed drivers have missing type annotations, resulting in warnings with this set to true. All PIXILAB code, however, compile without errors with this set to true. So I guess this was flipped along the way to avoid those. I don't really know when. Would make sense to clean up (or remove) those drivers I guess.

**Comment by AndersHogqvist** [comment]
I've checked now and the errors I get when enabling noImplicitAny were all referring to a few drivers (AnthemMRX_x20,  OSCviaUDP,  QSYS and EnttecSPlay). After removing them the console looked nice and clean again 🙂

**Comment by TheWizz** [comment]
Yes, that's correct. Those drivers are contributed by other users. So I prefer not to start "fixing" them in this regard. After all, they do work OK, so "if it ain't broke, don't fix it". So either keep noImplicitAny set to false to not see the errors, set it to true and live with the errors in those drivers, or just remove those drivers from your own working copy.

**Comment by mikaraunio** [comment]
Mea culpa. Have fixed the offendings bits in QSYS.ts

**Comment by TheWizz** [comment]
Is a pull request forthcoming?

Mike
