### ISSUE TITLE
Typescript dependency, JS execution environment

### ISSUE THREAD

**Issue by mikaraunio** [pixilab/blocks-script#29]
Could `typescript` be added as a project dependency? I believe Microsoft recommends this instead of relying of a globally installed version, but more importantly, it would make it explicit to script developers which version is supported.

Tangentially, is there documentation specifying which JS features are supported? I see `tsconfig.json` specifies ES5, but I'm getting errors for some things which have been supported for a long time (`Array.prototype.map()` for one doesn't seem to work).

**Comment by TheWizz** [comment]
Good idea. I'll add Typescript as a dev dependency in the 6.1 release. As to the language compatibility level, the Javascript implementation used in Blocks is based on the ECMAScript 5.1 specification. More details here:

https://developer.oracle.com/learn/technical-articles/nashorn-javascript-part1
