### ISSUE TITLE
Add support to set retain flag for mqtt publishing

### ISSUE THREAD

**Issue by larsemil** [pixilab/blocks-script#38]
MQTT has support to set retain flag for mqtt publications. 
I would love to see this support in the mqtt driver.

**Comment by TheWizz** [comment]
Would merely adding a "retain" option to the current sendText API be sufficient?

Mike

**Comment by larsemil** [comment]
I have not looked at implementing it in API yet. But ideal would be to put a flag in the configuration:

```
[{
		"property": "NumPropName",
		"subTopic": "some/sub/topicWithNumericValue",
		"description": "Descriptive text shown in Blocks editor",
		"readOnly": true,
                "retain": true, 
		"dataType": "Number", "min": 1, "max": 10
	 }]
```

**Comment by TheWizz** [comment]
Yes, that would be a good place to control the retain flag of outgoing messages from the ConfigurableMQTT driver. However, for the driver to be able to apply this, it would still have to go into the API. I'm also considering adding a global setting on the MQTT network device itself, controlling the default behavior here, which would be convenient in cases where you want ALL outgoing messages to have retain either on or off, then not having to specify this explicitly in every call.

**Comment by larsemil** [comment]
Yes. Both ways would be preferred. 
Setting a default and also being able to set for certain topics. 

I started looking into the code, but I could not find where the actual MQTT code would be happening?

**Comment by TheWizz** [comment]
OK, this will be added to Blocks 6.2, both with a per-device checkbox controlling the default behavior and the ability to override this from drivers.

**Comment by TheWizz** [comment]
FYI, there will also be an optional flag, as per your suggestion, in the ConfigurableMQTT driver.
